osx_image: xcode9
language: objective-c

before_install:
  - gem install xcpretty

script:
  - swift test
  # - swift package generate-xcodeproj
  # - xcodebuild test -scheme CNKit-Package | xcpretty

# after_success:
#   - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
